import Head from "next/head"
import Image from "next/image"
import { Inter } from "next/font/google"
import styles from "@styles/Home.module.css";

import Navbar from "@components/navbar";
import { Modal } from "@components/modal";

const inter = Inter({ subsets: ["latin"] });
export default function Home() {
	return (
		<>
			<Head>
				<title>MC Mod Manager</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div className={styles["flex-container"]}>
				<Navbar/>

				<div className={styles["window"]}>

				</div>

				{/* <div className={styles["sidebar"]}>

				</div> */}
			</div>
		</>
	)
}
