
// WARNING:
// THIS PROJECT IS UNDER **HEAVY, HEAVY, HEAVY* DEVELOPMENT
// IF YOU AREN'T A POTATO SMP PLAYER, YOU WILL NOT BE GIVEN SUPPORT FOR IT!

import { useState } from "react";
import Head from "next/head"
import Image from "next/image"
import { Inter } from "next/font/google"
import styles from "@styles/Home.module.css";
import navStyles from "@components/navbar/navbar.module.css";
import globalStyles from "@styles/globalLib.module.css";

import Navbar from "@components/navbar";
import { Modal } from "@components/modal";
import { Button } from "@components/button";

import { invoke } from '@tauri-apps/api/tauri'

const inter = Inter({ subsets: ["latin"] });
export default function Home() {
	const [active, setActive] = useState("CurseForge");
	const [status, setStatus] = useState("");
	const [isOn, setIsOn] = useState(true);

	function buttonPress() {
		setStatus("Installing...");
		invoke("download_potatosmp", { isOn: isOn }).then((response) => {
			const response_string = response as string;
			setStatus(response_string);
		})
	}

	return (
		<>
			<Head>
				<title>Nebula Launcher</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div className={styles["fullscreen-flex-container"]}>
				<div id={styles["potato-smp"]}>
					<h1>Potato SMP</h1>
					
					<div className={styles["flex-container-center"]}>
						<input onChange={() => setIsOn(!isOn)} type="checkbox" id={"hi"} checked={isOn}/>
						<label htmlFor="input-box" id={styles["input-box-label"]}>Include performance-intensive mods</label><br/>
					</div>
					<Button onClick={buttonPress}text="Install" color="var(--mg2-color)"></Button>
					<p>{status}</p>
				</div>
				
			</div>
			<p id={styles.tempP}>WARNING: This is an alpha, alpha, ALPHA version of the Nebula Launcher. It only works to install the Potato SMP X modpack currently.</p>
			<p id={styles.tempP}>This design is nowhere near final as this is just the bare minimum for this to currently work.</p>
			

			{/* <div className={globalStyles["flex-container"]}>
				<nav>
					<a href="./"><h2>Nebula Launcher</h2></a>

					<h3>Install</h3>
						<div className={navStyles["flex-container"]}>
							<ul>
								<li onClick={() => setActive("CurseForge")}><a>CurseForge</a></li>
								<li onClick={() => setActive("Modrinth")}><a>Modrinth</a></li>
								<li onClick={() => setActive("Custom")}><a>Custom</a></li>
							</ul>
							
							{active === "Custom" && <Modal title="Custom" width="200px" height="150px"></Modal>}
						</div>

						<h3>Create</h3>
						<p>Coming soon!</p>
				</nav>

				<div className={styles["window"]}>
					{
						active === "CurseForge" &&
						<div className={styles["flex-container-center"]}>
							<div className={styles["test-window"]}>

							</div>

							<div className={styles["test-window"]}>

							</div>

							<div className={styles["test-window"]}>

							</div>

							<div className={styles["test-window"]}>

							</div>
						</div>
					}
				</div>

				{active === "CurseForge" && <div className={styles["sidebar"]}></div>}
			</div> */}
		</>
	)
}
